name: 'COPY script'
description: 'Copy script'

inputs:
    vps_host:
        description: 'vps_host'
        required: true
    vps_user:
        description: 'vps_user'
        required: true
    vps_ssh_key:
        description: 'vps_ssh_key'
        required: true
    port:
        description: 'port'
        default: '22'
        required: false


runs:
    using: "composite"
    steps:
        -   name: Copy deploy script to VPS
            uses: appleboy/scp-action@v1
            with:
                host: ${{ inputs.vps_host }}
                username: ${{ inputs.vps_user }}
                key: ${{ inputs.vps_ssh_key }}
                port: ${{ inputs.port }}
                source: .github/scripts/deploy-environment.sh
                target: /opt/finance