name: CI
run-name: CI checks for ${{ github.ref_name }} by @${{ github.actor }}
on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Check the quality of code style
        runs-on: ubuntu-20.04

        steps:
            -   uses: actions/checkout@v7
            -   uses: ./.github/actions/setup-project

            -   name: test ts files
                run: npm run typecheck



    typecheck:
        name: Check the quality of types
        runs-on: ubuntu-20.04

        steps:
            -   uses: actions/checkout@v7
            -   uses: ./.github/actions/setup-project
            -   name: test lint
                run: npm run lint

    build:
        name: Build
        runs-on: ubuntu-20.04
        needs: [lint, typecheck]

        steps:
            -   uses: actions/checkout@v7
            -   uses: ./.github/actions/setup-project

            -   name: Build
                run: npm run build
            -   name: Upload dist artifact
                uses: actions/upload-artifact@v7
                if: github.event_name == 'push' && github.ref == 'refs/heads/master'
                with:
                    name: dist
                    path: dist-${{ github.event.pull_request.number }}

    comment_to_pr:
        name: Comment about success
        runs-on: ubuntu-20.04
        needs: [build]
        if: github.event_name == 'pull_request'

        steps:
            -   uses: actions/github-script@v9
                with:
                    script: |
                        github.rest.issues.createComment({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.issue.number,
                            body: '✅ CI passed'
                        })