name: deploy-qa.yml
on:
    workflow_dispatch:
        inputs:
            image_tag:
                description: Docker image to deploy
                required: true
                type: string

jobs:
    deploy-qa:
        runs-on: ubuntu-latest
        environment: qa

        steps:
            -   uses: actions/checkout@v7
            -   uses: ./.github/actions/copy-script
                with:
                    vps_host: ${{ secrets.VPS_HOST }}
                    vps_user: ${{ secrets.VPS_USER }}
                    vps_ssh_key: ${{ secrets.VPS_SSH_KEY }}

            -   name: Deploy QA
                uses: appleboy/ssh-action@v1
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USER }}
                    key: ${{ secrets.VPS_SSH_KEY }}
                    port: 22
                    script: |
                        chmod +x /opt/finance/.github/scripts/deploy-environment.sh
                        
                        /opt/finance/.github/scripts/deploy-environment.sh \
                            qa \
                            "ghcr.io/tema-pomortsev/finance:${{ inputs.image_tag }}" \
                            finance-qa \
                            .env.qa \
                            compose.qa.yml